// <auto-generated />
using System;
using ConceptBed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConceptBed.Data.Migrations;

[DbContext(typeof(ConceptContext))]
partial class ConceptContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .UseCollation("NOCASE")
            .HasAnnotation("ProductVersion", "6.0.1");

        modelBuilder.Entity("ConceptBed.Data.Models.WeatherForecast", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<DateTime>("Date")
                    .HasColumnType("TEXT")
                    .HasColumnName("date");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER")
                    .HasColumnName("status");

                b.Property<string>("Summary")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("summary")
                    .UseCollation("NOCASE");

                b.Property<int>("Temperature")
                    .HasColumnType("INTEGER")
                    .HasColumnName("temperature");

                b.HasKey("Id");

                b.ToTable("forecasts", (string)null);

                b.HasData(
                    new
                    {
                        Id = new Guid("f6d40bcb-9cf8-472a-9b9e-e31bcf75e3fe"),
                        Date = new DateTime(2022, 1, 4, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3080),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = -16
                    },
                    new
                    {
                        Id = new Guid("e5526ad2-2ec5-428a-b1dc-0d45878bacfc"),
                        Date = new DateTime(2022, 1, 5, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3120),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = 36
                    },
                    new
                    {
                        Id = new Guid("63064af7-4fce-413a-b102-e0560701cd21"),
                        Date = new DateTime(2022, 1, 6, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3123),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = -14
                    },
                    new
                    {
                        Id = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e"),
                        Date = new DateTime(2022, 1, 7, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3125),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = 28
                    },
                    new
                    {
                        Id = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7"),
                        Date = new DateTime(2022, 1, 8, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3127),
                        Status = 0,
                        Summary = "Hot",
                        Temperature = 11
                    },
                    new
                    {
                        Id = new Guid("1bcbc2e0-6b6e-4155-9164-c66e397c1a71"),
                        Date = new DateTime(2022, 1, 9, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3130),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = -17
                    },
                    new
                    {
                        Id = new Guid("1d6065c5-c276-4c7b-ba7a-efd7554c4a03"),
                        Date = new DateTime(2022, 1, 10, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3132),
                        Status = 0,
                        Summary = "Warm",
                        Temperature = 27
                    },
                    new
                    {
                        Id = new Guid("a6dbfbd6-68f7-4bb0-8e03-ad90a9a1e723"),
                        Date = new DateTime(2022, 1, 11, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3134),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = -16
                    },
                    new
                    {
                        Id = new Guid("16cdf4f5-88c4-4f42-a86b-28987d13fb2c"),
                        Date = new DateTime(2022, 1, 12, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3136),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = -6
                    },
                    new
                    {
                        Id = new Guid("b19977e1-5244-430f-92da-f63d327e3656"),
                        Date = new DateTime(2022, 1, 13, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3138),
                        Status = 0,
                        Summary = "Balmy",
                        Temperature = -3
                    },
                    new
                    {
                        Id = new Guid("deabb045-cb23-43d7-836d-6ac10e3f5dcd"),
                        Date = new DateTime(2022, 1, 14, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3141),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = 48
                    },
                    new
                    {
                        Id = new Guid("d4fe1aa7-79f3-45c2-ba10-14fb61d5b9e2"),
                        Date = new DateTime(2022, 1, 15, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3142),
                        Status = 0,
                        Summary = "Balmy",
                        Temperature = 29
                    },
                    new
                    {
                        Id = new Guid("a1ff6cd0-33b0-4631-b92b-ac3f41a2218b"),
                        Date = new DateTime(2022, 1, 16, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3144),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = -16
                    },
                    new
                    {
                        Id = new Guid("385efb01-53ac-4aa0-8073-4ed268cd74b4"),
                        Date = new DateTime(2022, 1, 17, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3146),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = 4
                    },
                    new
                    {
                        Id = new Guid("20b1bdc1-2002-4126-9194-6a05f6b5be22"),
                        Date = new DateTime(2022, 1, 18, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3148),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = 8
                    },
                    new
                    {
                        Id = new Guid("e09a90de-3b62-446f-a494-ca61c7d55a4a"),
                        Date = new DateTime(2022, 1, 19, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3150),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = 41
                    },
                    new
                    {
                        Id = new Guid("c017fb43-9ded-4628-b994-ecbb9536f937"),
                        Date = new DateTime(2022, 1, 20, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3152),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = -10
                    },
                    new
                    {
                        Id = new Guid("eeaf645c-3eb3-4c95-8d12-60b8d4a31bf9"),
                        Date = new DateTime(2022, 1, 21, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3154),
                        Status = 0,
                        Summary = "Balmy",
                        Temperature = 29
                    },
                    new
                    {
                        Id = new Guid("cfa22e8c-764d-43d5-8774-95df3a5d7a3e"),
                        Date = new DateTime(2022, 1, 22, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3156),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = -20
                    },
                    new
                    {
                        Id = new Guid("d612a7b5-97e1-46a0-aaeb-9e2a22638ca8"),
                        Date = new DateTime(2022, 1, 23, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3158),
                        Status = 0,
                        Summary = "Warm",
                        Temperature = -10
                    },
                    new
                    {
                        Id = new Guid("926c36d9-2371-48d5-a793-affd5529d7e5"),
                        Date = new DateTime(2022, 1, 24, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3160),
                        Status = 0,
                        Summary = "Hot",
                        Temperature = 10
                    },
                    new
                    {
                        Id = new Guid("4ceebb94-2283-47db-9257-245160b03736"),
                        Date = new DateTime(2022, 1, 25, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3162),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = -18
                    },
                    new
                    {
                        Id = new Guid("ff49ac02-60b2-44f4-bb63-c54dcecf28c9"),
                        Date = new DateTime(2022, 1, 26, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3163),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = 31
                    },
                    new
                    {
                        Id = new Guid("5cf9c4b5-11db-42ad-afb8-3941c533ad80"),
                        Date = new DateTime(2022, 1, 27, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3165),
                        Status = 0,
                        Summary = "Mild",
                        Temperature = 10
                    },
                    new
                    {
                        Id = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b"),
                        Date = new DateTime(2022, 1, 28, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3167),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = 46
                    },
                    new
                    {
                        Id = new Guid("522b2308-f0ca-46e0-a03e-565b959bc4c1"),
                        Date = new DateTime(2022, 1, 29, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3169),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = -10
                    },
                    new
                    {
                        Id = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93"),
                        Date = new DateTime(2022, 1, 30, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3171),
                        Status = 0,
                        Summary = "Balmy",
                        Temperature = 13
                    },
                    new
                    {
                        Id = new Guid("2e6de217-1ad4-4534-ad33-8e94af532c57"),
                        Date = new DateTime(2022, 1, 31, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3173),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = -6
                    },
                    new
                    {
                        Id = new Guid("9d15b3ff-1c3b-4e29-9568-528fdf662752"),
                        Date = new DateTime(2022, 2, 1, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3175),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = -9
                    },
                    new
                    {
                        Id = new Guid("4d17393b-bcbe-40fa-b7d2-acb507c2e9b4"),
                        Date = new DateTime(2022, 2, 2, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3177),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = 39
                    },
                    new
                    {
                        Id = new Guid("f09748d7-cc12-4bfc-9a6d-baf18fa87899"),
                        Date = new DateTime(2022, 2, 3, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3179),
                        Status = 0,
                        Summary = "Warm",
                        Temperature = 42
                    },
                    new
                    {
                        Id = new Guid("aa4d900b-02fa-4ba4-810a-536fd527f5d9"),
                        Date = new DateTime(2022, 2, 4, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3181),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = -5
                    },
                    new
                    {
                        Id = new Guid("9ed991da-6acc-430e-a2e8-f4087fdc829d"),
                        Date = new DateTime(2022, 2, 5, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3183),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = 40
                    },
                    new
                    {
                        Id = new Guid("be2569f0-433f-4345-ac74-d6ffa327f187"),
                        Date = new DateTime(2022, 2, 6, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3185),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = -4
                    },
                    new
                    {
                        Id = new Guid("f2161019-dabc-4539-9d14-7a82ee4e67af"),
                        Date = new DateTime(2022, 2, 7, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3187),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = 4
                    },
                    new
                    {
                        Id = new Guid("cef08291-9415-428c-8985-35116ddcb8ee"),
                        Date = new DateTime(2022, 2, 8, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3189),
                        Status = 0,
                        Summary = "Freezing",
                        Temperature = 33
                    },
                    new
                    {
                        Id = new Guid("a30af001-2c7e-489f-9f40-6ffe301bba76"),
                        Date = new DateTime(2022, 2, 9, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3191),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = 34
                    },
                    new
                    {
                        Id = new Guid("f8354bd6-0e09-4961-b199-a882a0f1069d"),
                        Date = new DateTime(2022, 2, 10, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3193),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = 22
                    },
                    new
                    {
                        Id = new Guid("71135c31-128e-43d6-88fa-8184f4bf7369"),
                        Date = new DateTime(2022, 2, 11, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3195),
                        Status = 0,
                        Summary = "Balmy",
                        Temperature = 1
                    },
                    new
                    {
                        Id = new Guid("03168dd9-83e4-4f53-b781-a8c8dbdc6e16"),
                        Date = new DateTime(2022, 2, 12, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3197),
                        Status = 0,
                        Summary = "Mild",
                        Temperature = -7
                    },
                    new
                    {
                        Id = new Guid("9d0a0f32-9ac9-4890-b23c-e7188ba6f6de"),
                        Date = new DateTime(2022, 2, 13, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3199),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = 22
                    },
                    new
                    {
                        Id = new Guid("94c48419-63de-4743-8198-a06755d8ee6a"),
                        Date = new DateTime(2022, 2, 14, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3227),
                        Status = 0,
                        Summary = "Mild",
                        Temperature = 20
                    },
                    new
                    {
                        Id = new Guid("00d2ecb6-ea0b-4d73-a087-a30a2d580150"),
                        Date = new DateTime(2022, 2, 15, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3229),
                        Status = 0,
                        Summary = "Bracing",
                        Temperature = -18
                    },
                    new
                    {
                        Id = new Guid("3e91b042-9666-4baa-bb1d-5057e1b614eb"),
                        Date = new DateTime(2022, 2, 16, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3231),
                        Status = 0,
                        Summary = "Warm",
                        Temperature = 48
                    },
                    new
                    {
                        Id = new Guid("4a50a294-1da6-45ab-928b-ed1ee39f96bf"),
                        Date = new DateTime(2022, 2, 17, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3233),
                        Status = 0,
                        Summary = "Chilly",
                        Temperature = 35
                    },
                    new
                    {
                        Id = new Guid("d3cfee22-66dc-4828-90fb-1c8ee7627355"),
                        Date = new DateTime(2022, 2, 18, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3235),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = -12
                    },
                    new
                    {
                        Id = new Guid("3f081475-12c0-4b4c-8f97-cbe7e54e9034"),
                        Date = new DateTime(2022, 2, 19, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3237),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = 20
                    },
                    new
                    {
                        Id = new Guid("0e774bcb-05f5-4eed-9d9d-883947c34442"),
                        Date = new DateTime(2022, 2, 20, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3239),
                        Status = 0,
                        Summary = "Cool",
                        Temperature = 33
                    },
                    new
                    {
                        Id = new Guid("c73ee724-894b-4e9c-8793-30d3e948f0c8"),
                        Date = new DateTime(2022, 2, 21, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3240),
                        Status = 0,
                        Summary = "Scorching",
                        Temperature = 7
                    },
                    new
                    {
                        Id = new Guid("fe1e9320-baeb-4561-88de-e11694387c91"),
                        Date = new DateTime(2022, 2, 22, 20, 16, 4, 625, DateTimeKind.Local).AddTicks(3243),
                        Status = 0,
                        Summary = "Warm",
                        Temperature = 17
                    });
            });

        modelBuilder.Entity("ConceptBed.Data.Models.WeatherLogEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("Date")
                    .HasColumnType("TEXT")
                    .HasColumnName("date");

                b.Property<int>("Delta")
                    .HasColumnType("INTEGER")
                    .HasColumnName("delta");

                b.Property<Guid>("ForecastId")
                    .HasColumnType("TEXT")
                    .HasColumnName("forecast_id");

                b.HasKey("Id");

                b.HasIndex("ForecastId");

                b.ToTable("forecastdeltas", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1420761322,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3357),
                        Delta = 6,
                        ForecastId = new Guid("9ed991da-6acc-430e-a2e8-f4087fdc829d")
                    },
                    new
                    {
                        Id = 280214241,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3384),
                        Delta = -6,
                        ForecastId = new Guid("63064af7-4fce-413a-b102-e0560701cd21")
                    },
                    new
                    {
                        Id = 2011699160,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3385),
                        Delta = 4,
                        ForecastId = new Guid("a6dbfbd6-68f7-4bb0-8e03-ad90a9a1e723")
                    },
                    new
                    {
                        Id = 1980081103,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3386),
                        Delta = 2,
                        ForecastId = new Guid("cfa22e8c-764d-43d5-8774-95df3a5d7a3e")
                    },
                    new
                    {
                        Id = 1689081071,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3386),
                        Delta = -6,
                        ForecastId = new Guid("cfa22e8c-764d-43d5-8774-95df3a5d7a3e")
                    },
                    new
                    {
                        Id = 1899968073,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3388),
                        Delta = -10,
                        ForecastId = new Guid("1d6065c5-c276-4c7b-ba7a-efd7554c4a03")
                    },
                    new
                    {
                        Id = 295178657,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3389),
                        Delta = -3,
                        ForecastId = new Guid("f6d40bcb-9cf8-472a-9b9e-e31bcf75e3fe")
                    },
                    new
                    {
                        Id = 1830872492,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3390),
                        Delta = 0,
                        ForecastId = new Guid("c73ee724-894b-4e9c-8793-30d3e948f0c8")
                    },
                    new
                    {
                        Id = 1788084648,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3390),
                        Delta = 6,
                        ForecastId = new Guid("63064af7-4fce-413a-b102-e0560701cd21")
                    },
                    new
                    {
                        Id = 658766812,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3392),
                        Delta = 0,
                        ForecastId = new Guid("4a50a294-1da6-45ab-928b-ed1ee39f96bf")
                    },
                    new
                    {
                        Id = 98769182,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3392),
                        Delta = -10,
                        ForecastId = new Guid("03168dd9-83e4-4f53-b781-a8c8dbdc6e16")
                    },
                    new
                    {
                        Id = 1684092101,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3393),
                        Delta = 9,
                        ForecastId = new Guid("ff49ac02-60b2-44f4-bb63-c54dcecf28c9")
                    },
                    new
                    {
                        Id = 545119316,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3394),
                        Delta = -4,
                        ForecastId = new Guid("4a50a294-1da6-45ab-928b-ed1ee39f96bf")
                    },
                    new
                    {
                        Id = 79300082,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3395),
                        Delta = 7,
                        ForecastId = new Guid("ff49ac02-60b2-44f4-bb63-c54dcecf28c9")
                    },
                    new
                    {
                        Id = 786269710,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3395),
                        Delta = -2,
                        ForecastId = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7")
                    },
                    new
                    {
                        Id = 1313090666,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3396),
                        Delta = -6,
                        ForecastId = new Guid("a30af001-2c7e-489f-9f40-6ffe301bba76")
                    },
                    new
                    {
                        Id = 1927414160,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3396),
                        Delta = 6,
                        ForecastId = new Guid("00d2ecb6-ea0b-4d73-a087-a30a2d580150")
                    },
                    new
                    {
                        Id = 353526859,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3398),
                        Delta = -7,
                        ForecastId = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b")
                    },
                    new
                    {
                        Id = 1811087311,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3399),
                        Delta = -10,
                        ForecastId = new Guid("aa4d900b-02fa-4ba4-810a-536fd527f5d9")
                    },
                    new
                    {
                        Id = 766947535,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3400),
                        Delta = 9,
                        ForecastId = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e")
                    },
                    new
                    {
                        Id = 218105496,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3400),
                        Delta = -3,
                        ForecastId = new Guid("20b1bdc1-2002-4126-9194-6a05f6b5be22")
                    },
                    new
                    {
                        Id = 387581386,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3401),
                        Delta = -5,
                        ForecastId = new Guid("b19977e1-5244-430f-92da-f63d327e3656")
                    },
                    new
                    {
                        Id = 86466933,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3402),
                        Delta = 0,
                        ForecastId = new Guid("f6d40bcb-9cf8-472a-9b9e-e31bcf75e3fe")
                    },
                    new
                    {
                        Id = 1320818638,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3403),
                        Delta = -9,
                        ForecastId = new Guid("9ed991da-6acc-430e-a2e8-f4087fdc829d")
                    },
                    new
                    {
                        Id = 1604691917,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3403),
                        Delta = -2,
                        ForecastId = new Guid("c017fb43-9ded-4628-b994-ecbb9536f937")
                    },
                    new
                    {
                        Id = 219813315,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3404),
                        Delta = -4,
                        ForecastId = new Guid("ff49ac02-60b2-44f4-bb63-c54dcecf28c9")
                    },
                    new
                    {
                        Id = 695372853,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3405),
                        Delta = -5,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    },
                    new
                    {
                        Id = 1450587950,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3405),
                        Delta = -9,
                        ForecastId = new Guid("cfa22e8c-764d-43d5-8774-95df3a5d7a3e")
                    },
                    new
                    {
                        Id = 2027064651,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3406),
                        Delta = -6,
                        ForecastId = new Guid("cef08291-9415-428c-8985-35116ddcb8ee")
                    },
                    new
                    {
                        Id = 1800288968,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3406),
                        Delta = -6,
                        ForecastId = new Guid("a1ff6cd0-33b0-4631-b92b-ac3f41a2218b")
                    },
                    new
                    {
                        Id = 1412936112,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3407),
                        Delta = 6,
                        ForecastId = new Guid("f6d40bcb-9cf8-472a-9b9e-e31bcf75e3fe")
                    },
                    new
                    {
                        Id = 554176475,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3408),
                        Delta = 8,
                        ForecastId = new Guid("4d17393b-bcbe-40fa-b7d2-acb507c2e9b4")
                    },
                    new
                    {
                        Id = 1403308658,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3409),
                        Delta = 8,
                        ForecastId = new Guid("0e774bcb-05f5-4eed-9d9d-883947c34442")
                    },
                    new
                    {
                        Id = 280883664,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3410),
                        Delta = -8,
                        ForecastId = new Guid("63064af7-4fce-413a-b102-e0560701cd21")
                    },
                    new
                    {
                        Id = 48237451,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3411),
                        Delta = -10,
                        ForecastId = new Guid("0e774bcb-05f5-4eed-9d9d-883947c34442")
                    },
                    new
                    {
                        Id = 982515892,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3411),
                        Delta = 4,
                        ForecastId = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b")
                    },
                    new
                    {
                        Id = 1875751644,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3412),
                        Delta = -4,
                        ForecastId = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b")
                    },
                    new
                    {
                        Id = 410839834,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3412),
                        Delta = 0,
                        ForecastId = new Guid("3f081475-12c0-4b4c-8f97-cbe7e54e9034")
                    },
                    new
                    {
                        Id = 1942298856,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3413),
                        Delta = -7,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    },
                    new
                    {
                        Id = 1910023354,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3414),
                        Delta = 6,
                        ForecastId = new Guid("f8354bd6-0e09-4961-b199-a882a0f1069d")
                    },
                    new
                    {
                        Id = 652681011,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3414),
                        Delta = -8,
                        ForecastId = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e")
                    },
                    new
                    {
                        Id = 1299389449,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3415),
                        Delta = 6,
                        ForecastId = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7")
                    },
                    new
                    {
                        Id = 773264466,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3416),
                        Delta = 9,
                        ForecastId = new Guid("4a50a294-1da6-45ab-928b-ed1ee39f96bf")
                    },
                    new
                    {
                        Id = 385306698,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3416),
                        Delta = 4,
                        ForecastId = new Guid("e5526ad2-2ec5-428a-b1dc-0d45878bacfc")
                    },
                    new
                    {
                        Id = 1784290922,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3417),
                        Delta = 1,
                        ForecastId = new Guid("1d6065c5-c276-4c7b-ba7a-efd7554c4a03")
                    },
                    new
                    {
                        Id = 817945308,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3418),
                        Delta = 4,
                        ForecastId = new Guid("a6dbfbd6-68f7-4bb0-8e03-ad90a9a1e723")
                    },
                    new
                    {
                        Id = 1544583733,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3419),
                        Delta = 6,
                        ForecastId = new Guid("5cf9c4b5-11db-42ad-afb8-3941c533ad80")
                    },
                    new
                    {
                        Id = 138568179,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3419),
                        Delta = 1,
                        ForecastId = new Guid("522b2308-f0ca-46e0-a03e-565b959bc4c1")
                    },
                    new
                    {
                        Id = 2021716432,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3420),
                        Delta = 3,
                        ForecastId = new Guid("aa4d900b-02fa-4ba4-810a-536fd527f5d9")
                    },
                    new
                    {
                        Id = 1482429577,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3421),
                        Delta = 2,
                        ForecastId = new Guid("d4fe1aa7-79f3-45c2-ba10-14fb61d5b9e2")
                    },
                    new
                    {
                        Id = 255177018,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3421),
                        Delta = 1,
                        ForecastId = new Guid("1bcbc2e0-6b6e-4155-9164-c66e397c1a71")
                    },
                    new
                    {
                        Id = 434940346,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3422),
                        Delta = 9,
                        ForecastId = new Guid("4a50a294-1da6-45ab-928b-ed1ee39f96bf")
                    },
                    new
                    {
                        Id = 1076043683,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3423),
                        Delta = -1,
                        ForecastId = new Guid("cef08291-9415-428c-8985-35116ddcb8ee")
                    },
                    new
                    {
                        Id = 85068063,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3424),
                        Delta = 9,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    },
                    new
                    {
                        Id = 1808662283,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3424),
                        Delta = 3,
                        ForecastId = new Guid("63064af7-4fce-413a-b102-e0560701cd21")
                    },
                    new
                    {
                        Id = 2126856789,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3425),
                        Delta = 7,
                        ForecastId = new Guid("c017fb43-9ded-4628-b994-ecbb9536f937")
                    },
                    new
                    {
                        Id = 619049975,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3426),
                        Delta = 1,
                        ForecastId = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b")
                    },
                    new
                    {
                        Id = 1665336649,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3426),
                        Delta = -7,
                        ForecastId = new Guid("385efb01-53ac-4aa0-8073-4ed268cd74b4")
                    },
                    new
                    {
                        Id = 6203975,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3427),
                        Delta = -3,
                        ForecastId = new Guid("00d2ecb6-ea0b-4d73-a087-a30a2d580150")
                    },
                    new
                    {
                        Id = 1537085669,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3428),
                        Delta = -1,
                        ForecastId = new Guid("926c36d9-2371-48d5-a793-affd5529d7e5")
                    },
                    new
                    {
                        Id = 216723576,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3429),
                        Delta = -7,
                        ForecastId = new Guid("9ed991da-6acc-430e-a2e8-f4087fdc829d")
                    },
                    new
                    {
                        Id = 132471460,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3429),
                        Delta = -3,
                        ForecastId = new Guid("f8354bd6-0e09-4961-b199-a882a0f1069d")
                    },
                    new
                    {
                        Id = 1953009193,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3430),
                        Delta = -1,
                        ForecastId = new Guid("16cdf4f5-88c4-4f42-a86b-28987d13fb2c")
                    },
                    new
                    {
                        Id = 1781699236,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3431),
                        Delta = 5,
                        ForecastId = new Guid("9d0a0f32-9ac9-4890-b23c-e7188ba6f6de")
                    },
                    new
                    {
                        Id = 725382147,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3432),
                        Delta = -3,
                        ForecastId = new Guid("9d15b3ff-1c3b-4e29-9568-528fdf662752")
                    },
                    new
                    {
                        Id = 678146833,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3433),
                        Delta = 2,
                        ForecastId = new Guid("d4fe1aa7-79f3-45c2-ba10-14fb61d5b9e2")
                    },
                    new
                    {
                        Id = 1870484471,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3434),
                        Delta = -6,
                        ForecastId = new Guid("4d17393b-bcbe-40fa-b7d2-acb507c2e9b4")
                    },
                    new
                    {
                        Id = 2051865847,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3435),
                        Delta = -1,
                        ForecastId = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7")
                    },
                    new
                    {
                        Id = 1401203327,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3435),
                        Delta = 6,
                        ForecastId = new Guid("cef08291-9415-428c-8985-35116ddcb8ee")
                    },
                    new
                    {
                        Id = 2103768634,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3436),
                        Delta = -6,
                        ForecastId = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7")
                    },
                    new
                    {
                        Id = 590097170,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3437),
                        Delta = -2,
                        ForecastId = new Guid("20b1bdc1-2002-4126-9194-6a05f6b5be22")
                    },
                    new
                    {
                        Id = 216050304,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3437),
                        Delta = -10,
                        ForecastId = new Guid("1d6065c5-c276-4c7b-ba7a-efd7554c4a03")
                    },
                    new
                    {
                        Id = 1056475776,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3438),
                        Delta = -9,
                        ForecastId = new Guid("3e91b042-9666-4baa-bb1d-5057e1b614eb")
                    },
                    new
                    {
                        Id = 1795024923,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3439),
                        Delta = -6,
                        ForecastId = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e")
                    },
                    new
                    {
                        Id = 32725701,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3439),
                        Delta = -4,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    },
                    new
                    {
                        Id = 739901873,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3440),
                        Delta = -9,
                        ForecastId = new Guid("a30af001-2c7e-489f-9f40-6ffe301bba76")
                    },
                    new
                    {
                        Id = 139790624,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3441),
                        Delta = -9,
                        ForecastId = new Guid("ff49ac02-60b2-44f4-bb63-c54dcecf28c9")
                    },
                    new
                    {
                        Id = 1066959401,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3441),
                        Delta = 7,
                        ForecastId = new Guid("94c48419-63de-4743-8198-a06755d8ee6a")
                    },
                    new
                    {
                        Id = 1300586865,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3442),
                        Delta = 9,
                        ForecastId = new Guid("71135c31-128e-43d6-88fa-8184f4bf7369")
                    },
                    new
                    {
                        Id = 119057504,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3443),
                        Delta = -8,
                        ForecastId = new Guid("4d17393b-bcbe-40fa-b7d2-acb507c2e9b4")
                    },
                    new
                    {
                        Id = 652621621,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3443),
                        Delta = -10,
                        ForecastId = new Guid("a6dbfbd6-68f7-4bb0-8e03-ad90a9a1e723")
                    },
                    new
                    {
                        Id = 2126267819,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3444),
                        Delta = -4,
                        ForecastId = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e")
                    },
                    new
                    {
                        Id = 233536560,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3445),
                        Delta = -9,
                        ForecastId = new Guid("fb1f0f5d-4683-44ea-a805-437523e1289b")
                    },
                    new
                    {
                        Id = 324688154,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3445),
                        Delta = -3,
                        ForecastId = new Guid("f2161019-dabc-4539-9d14-7a82ee4e67af")
                    },
                    new
                    {
                        Id = 47892527,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3446),
                        Delta = 1,
                        ForecastId = new Guid("1d6065c5-c276-4c7b-ba7a-efd7554c4a03")
                    },
                    new
                    {
                        Id = 1583885227,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3446),
                        Delta = -9,
                        ForecastId = new Guid("2e6de217-1ad4-4534-ad33-8e94af532c57")
                    },
                    new
                    {
                        Id = 269892388,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3447),
                        Delta = -5,
                        ForecastId = new Guid("c017fb43-9ded-4628-b994-ecbb9536f937")
                    },
                    new
                    {
                        Id = 1820343591,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3448),
                        Delta = 0,
                        ForecastId = new Guid("a30af001-2c7e-489f-9f40-6ffe301bba76")
                    },
                    new
                    {
                        Id = 968207206,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3448),
                        Delta = 5,
                        ForecastId = new Guid("be2569f0-433f-4345-ac74-d6ffa327f187")
                    },
                    new
                    {
                        Id = 1635030280,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3449),
                        Delta = -2,
                        ForecastId = new Guid("3f081475-12c0-4b4c-8f97-cbe7e54e9034")
                    },
                    new
                    {
                        Id = 2042247979,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3450),
                        Delta = -5,
                        ForecastId = new Guid("b19977e1-5244-430f-92da-f63d327e3656")
                    },
                    new
                    {
                        Id = 689914792,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3451),
                        Delta = 0,
                        ForecastId = new Guid("4006dac0-c81d-402d-8569-43b6eb577e7e")
                    },
                    new
                    {
                        Id = 1922473469,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3451),
                        Delta = -10,
                        ForecastId = new Guid("531eb79c-d3bc-47d4-ac88-24a0fc9bb0c7")
                    },
                    new
                    {
                        Id = 572223304,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3452),
                        Delta = 2,
                        ForecastId = new Guid("d4fe1aa7-79f3-45c2-ba10-14fb61d5b9e2")
                    },
                    new
                    {
                        Id = 1374352893,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3452),
                        Delta = 7,
                        ForecastId = new Guid("f8354bd6-0e09-4961-b199-a882a0f1069d")
                    },
                    new
                    {
                        Id = 911872447,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3453),
                        Delta = 1,
                        ForecastId = new Guid("9d15b3ff-1c3b-4e29-9568-528fdf662752")
                    },
                    new
                    {
                        Id = 783812,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3454),
                        Delta = 3,
                        ForecastId = new Guid("eeaf645c-3eb3-4c95-8d12-60b8d4a31bf9")
                    },
                    new
                    {
                        Id = 289972459,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3455),
                        Delta = -9,
                        ForecastId = new Guid("b19977e1-5244-430f-92da-f63d327e3656")
                    },
                    new
                    {
                        Id = 17191306,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3455),
                        Delta = 8,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    },
                    new
                    {
                        Id = 1876863775,
                        Date = new DateTime(2022, 1, 4, 19, 16, 4, 625, DateTimeKind.Utc).AddTicks(3456),
                        Delta = -6,
                        ForecastId = new Guid("7f68b18c-72a1-468f-b55f-8b19d6a0db93")
                    });
            });

        modelBuilder.Entity("ConceptBed.Data.Models.WeatherLogEntry", b =>
            {
                b.HasOne("ConceptBed.Data.Models.WeatherForecast", null)
                    .WithMany("History")
                    .HasForeignKey("ForecastId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("ConceptBed.Data.Models.WeatherForecast", b =>
            {
                b.Navigation("History");
            });
#pragma warning restore 612, 618
    }
}
